import { REQUEST_SEARCH_CITY, RECEIVE_SEARCH_CITY,  CitySearchStates, SELECT_CITY, CHANGE_SEARCH_TEXT, RECEIVE_POIS, REQUEST_POIS, DRAG_START, DRAG_END, DRAG_MOVE, RECEIVE_CITY_IMAGE } from '../actions/actions'
	
